### ISSUE TITLE
Exit

### ISSUE THREAD

**Issue by paulahemsi** [paulahemsi/minishell#112]
![image](https://user-images.githubusercontent.com/63563271/127726487-04051352-93f3-4c80-9e7e-8450cf3cb2c6.png)

entender o que a régua quer dizer com `exit` com argumentos

**Comment by laisarena** [comment]
Segundo o subject não deveria ter argumento, mas o argumento é fácil de implementar. A gente implementa ou só coloca mensagem de erro para quando passar argumentos??
Independente de qualquer coisa acho legal fazer o minishell sair com o status certo. 

![image](https://user-images.githubusercontent.com/35609595/127750340-d1173033-895c-4bc6-a90a-7c7143f13dbe.png)


![image](https://user-images.githubusercontent.com/35609595/127750326-53dd6a53-ebfa-44c1-8f5e-42433c55d6db.png)
