### ISSUE TITLE
bugs gerais

### ISSUE THREAD

**Issue by gsenra** [paulahemsi/minishell#97]
>arquivo1 >arq2 >>    arqv3
seg (deveria criar)
OK

>a >b >>   c echo aaa
heap-buffer-overflow (deveria criar)
OK

echo aaa >a >b >>   c
OK

>arq1 >arqv2 >>arqv3
heap-buffer-overflow (deveria criar)
OK

<arv cat
heap-buffer-overflow
OK

echo >>arv abacaxi
ta substituindo e não incrementando no arquivo
OK

echo |
devia ler stand input ou fazer nada
OK

*****verificar expansao de variavel(local e exportada)****
echo >arq "lalalandia $banana"
heap-buffer-overflow 
OK

echo "lalalandia $banana" >xxx
heap-buffer-overflow 
OK

echo >aa "aspas$banana"
heap-buffer-overflow 
OK

AINDA FALTA:
echo >>  
bash: erro de sintaxe próximo ao token inesperado `newline'
OK

echo >  
bash: erro de sintaxe próximo ao token inesperado `newline'
OK

env bama
deveria retornar msg (env: “bama”: Arquivo ou diretório inexistente)
(NOT MANDATORY)

env banana=oi
se qser fazer, nesse caso, o env exportaria banana
(NOT MANDATORY)

**Comment by paulahemsi** [comment]
Todos os bugs mandatórios desta lista resolvidos! \o/

**Comment by paulahemsi** [comment]
Todos os bugs mandatórios desta lista resolvidos! \o/
